version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/target
    command: sleep infinity
    environment:
      - RUST_LOG=debug
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  cargo-cache:
  target-cache: