juser:
  name: kako-jun
  email: 3541096+kako-jun@users.noreply.github.com
comments:
  default: update.
repos:
  - ---:
    enabled: true
    name: curion
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/curion.git
  - ---:
    enabled: true
    name: esuna
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/esuna.git
  - ---:
    enabled: true
    name: sync-stone
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/sync-stone.git
  - ---:
    enabled: true
    name: benf
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/benf.git
  - ---:
    enabled: true
    name: amanuma
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/amanuma.git
  - ---:
    enabled: true
    name: neHTpNc
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/neHTpNc.git
  - ---:
    enabled: true
    name: stew-of-stars
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/stew-of-stars.git
  - ---:
    enabled: true
    name: retro-decode
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/retro-decode.git
  - ---:
    enabled: true
    name: cee-lo-rings
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/cee-lo-rings.git
  - ---:
    enabled: true
    name: yatagarrage
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/yatagarrage.git
  - ---:
    enabled: true
    name: photo-returns
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/photo-returns.git
  - ---:
    enabled: true
    name: nostalgic-bbs
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/nostalgic-bbs.git
  - ---:
    enabled: true
    name: nostalgic-counter
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/nostalgic-counter.git
  - ---:
    enabled: true
    name: tail-match
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/tail-match.git
  - ---:
    enabled: true
    name: noun-gender
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/noun-gender.git
  - ---:
    enabled: true
    name: sid-note
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/sid-note.git
  - ---:
    enabled: true
    name: llll-ll
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/llll-ll.git
  - ---:
    enabled: true
    name: nginx-proxy
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/nginx-proxy.git
  - ---:
    enabled: true
    name: sandbox
    group: 2025
    branch: main
    remote: git@github.com:kako-jun/sandbox.git
  - ---:
    enabled: false
    name: gitp
    group: 2024
    branch: main
    remote: git@github.com:kako-jun/gitp.git
  - ---:
    enabled: false
    name: photos_into_YYYY_YYYYMM_YYYYMMDD
    group: 2024
    branch: main
    remote: git@github.com:kako-jun/photos_into_YYYY_YYYYMM_YYYYMMDD.git
  - ---:
    enabled: false
    name: nostalgic_counter_server
    group: 2024
    branch: main
    remote: git@github.com:kako-jun/nostalgic_counter_server.git
  - ---:
    enabled: false
    name: nostalgic_counter_client
    group: 2024
    branch: main
    remote: git@github.com:kako-jun/nostalgic_counter_client.git
  - ---:
    enabled: false
    name: portal
    group: 2024
    branch: main
    remote: git@github.com:kako-jun/portal.git
  - ---:
    enabled: false
    name: white_owl_server
    group: 2024
    branch: main
    remote: git@github.com:kako-jun/white_owl_server.git
  - ---:
    enabled: false
    name: white_owl
    group: 2024
    branch: main
    remote: git@github.com:kako-jun/white_owl.git
  - ---:
    enabled: false
    name: kvns42
    group: 2024
    branch: main
    remote: git@github.com:kako-jun/kvns42.git
  - ---:
    enabled: false
    name: tin-tilo-rings
    group: 2024
    branch: main
    remote: git@github.com:kako-jun/tin-tilo-rings.git
  - ---:
    enabled: false
    name: amanuma
    group: 2024
    branch: main
    remote: git@github.com:kako-jun/amanuma.git
  - ---:
    enabled: false
    name: filmente
    group: 2024
    branch: main
    remote: git@github.com:kako-jun/filmente.git
  - ---:
    enabled: false
    name: dockerfiles
    group: learning
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/learning/dockerfiles
  - ---:
    enabled: false
    name: learning_scikit_learn
    group: learning
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/learning/learning_scikit_learn
  - ---:
    enabled: false
    name: learning_rust
    group: learning
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/learning/learning_rust
  - ---:
    enabled: false
    name: bbs
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/bbs
  - ---:
    enabled: false
    name: gist-exporter
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/gist-exporter
  - ---:
    enabled: false
    name: japanese-horror-film-effect
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/japanese-horror-film-effect
  - ---:
    enabled: false
    name: letter-icon-generator
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/letter-icon-generator
  - ---:
    enabled: false
    name: piccolo-egg
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/piccolo-egg
  - ---:
    enabled: false
    name: flags
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/flags
  - ---:
    enabled: false
    name: cat
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/cat
  - ---:
    enabled: false
    name: dragon-quest-4koma-manga-theater-forever
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/dragon-quest-4koma-manga-theater-forever
  - ---:
    enabled: false
    name: jpico_info
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/jpico_info
  - ---:
    enabled: false
    name: portal
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/portal
  - ---:
    enabled: false
    name: skirts-colour
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/skirts-colour
  - ---:
    enabled: false
    name: skirts-colour-spec
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/skirts-colour-spec
  - ---:
    enabled: false
    name: chara-spec
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/chara-spec
  - ---:
    enabled: false
    name: h-colour
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/h-colour
  - ---:
    enabled: false
    name: h-colour-spec
    group: salted
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/salted/h-colour-spec
  - ---:
    enabled: false
    name: clean
    group: common
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/common/clean
  - ---:
    enabled: false
    name: editing
    group: common
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/common/editing
  - ---:
    enabled: false
    name: writing
    group: common
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/common/writing
  - ---:
    enabled: false
    name: drawing
    group: common
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/common/drawing
  - ---:
    enabled: true
    name: home
    group: common
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/common/home
  - ---:
    enabled: true
    name: town
    group: common
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/common/town
  - ---:
    enabled: true
    name: setting
    group: common
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/common/setting
  - ---:
    enabled: true
    name: etc
    group: common
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/common/etc
  - ---:
    enabled: true
    name: work
    group: common
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/common/work
  - ---:
    enabled: false
    name: temp
    group: common
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/common/temp
  - ---:
    enabled: false
    name: egg
    group: common
    branch: main
    remote: git@ssh.dev.azure.com:v3/kako-jun2/common/egg
