[http]
check-revoke = false
timeout = 120

[net]
retry = 5
git-fetch-with-cli = true

[registry]
default = "crates-io"

[registries.crates-io]
index = "https://index.crates.io/"

# Modern Rust build configuration
[build]
rustflags = [
    "-D", "warnings",                    # Deny warnings
    "-D", "rust-2018-idioms",           # Use modern Rust idioms
    "-D", "future-incompatible",        # Catch future compatibility issues
    "-D", "nonstandard-style",          # Enforce standard naming conventions
    "-W", "missing-docs",               # Warn on missing documentation
    "-W", "rust-2021-compatibility",    # Rust 2021 edition compatibility
]

# Target-specific configurations
[target.'cfg(all(target_env = "msvc", target_arch = "x86_64"))']
rustflags = ["-C", "target-feature=+crt-static"]

# Development profile optimizations
[profile.dev]
# Enable some optimizations for better development experience
opt-level = 1
debug = true
split-debuginfo = "unpacked"

# Release profile optimizations
[profile.release]
opt-level = 3
debug = false
strip = true
lto = true
codegen-units = 1
panic = "abort"

# Test profile
[profile.test]
opt-level = 1
debug = true

# Alias for common commands
[alias]
b = "build"
br = "build --release"
t = "test"
c = "check"
cl = "clippy"
r = "run"
