[build]
  command = "pip install poetry && poetry install --no-root && poetry run python -m pygbag --width 800 --height 600 --no_opt main.py"
  publish = "build/web"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200