cognitive-complexity-threshold = 25
too-many-arguments-threshold = 8
too-many-lines-threshold = 300
type-complexity-threshold = 25
cyclomatic-complexity-threshold = 15
max-stack-size = 16
too-large-for-stack = 2048
too-many-locals-threshold = 30
too-many-branches-threshold = 20
too-many-statements-threshold = 50 