edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
format_code_in_doc_comments = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
format_macro_brace_style = "AlwaysNextLine"
format_macro_call_style = "AlwaysNextLine"
format_macro_arm_style = "AlwaysNextLine"
format_macro_arm_brace_style = "AlwaysNextLine"
format_macro_arm_separator = "AlwaysNextLine"
format_macro_arm_trailing_comma = "AlwaysNextLine"
format_macro_arm_leading_comma = "AlwaysNextLine"
format_macro_arm_leading_comma_style = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_always = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_never = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_auto = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_always_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_never_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_auto_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_always_vertical = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_never_vertical = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_auto_vertical = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_always_vertical_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_never_vertical_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_auto_vertical_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_always_vertical_always_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_never_vertical_always_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_auto_vertical_always_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_always_vertical_never_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_never_vertical_never_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_auto_vertical_never_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_always_vertical_auto_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_never_vertical_auto_next_line = "AlwaysNextLine"
format_macro_arm_leading_comma_style_force_auto_vertical_auto_next_line = "AlwaysNextLine" 