version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - ../logs:/workspace/logs
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/workspace
    ports:
      - "5000:5000"  # Web interface
      - "8000:8000"  # API server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5" 