# Clippy configuration

# Avoid false positives
avoid-breaking-exported-api = false

# Set the maximum number of lines a function can have
too-many-lines-threshold = 100

# Set the maximum number of arguments a function can have  
too-many-arguments-threshold = 7

# Set the maximum cognitive complexity for a function
cognitive-complexity-threshold = 30

# Set the maximum cyclomatic complexity for a function
cyclomatic-complexity-threshold = 25

# Allow certain lints that might be too strict for this project
allow = [
    "clippy::module_name_repetitions",
    "clippy::similar_names",
    "clippy::too_many_lines",
]

# Warn on these specific lints
warn = [
    "clippy::pedantic",
    "clippy::nursery",
    "clippy::cargo",
]

# Deny these lints (treat as errors)
deny = [
    "clippy::unwrap_used",
    "clippy::expect_used",
    "clippy::panic",
    "clippy::unimplemented",
    "clippy::todo",
]