# Docker Compose file for rust-tool-template
# Note: version field is deprecated in newer Docker Compose versions

services:
  rust-tool-template:
    build: .
    container_name: rust-tool-template
    restart: unless-stopped
    environment:
      - RUST_LOG=rust_tool_template=info
      - RUST_TOOL_LANG=en
      - RUST_BACKTRACE=1
    volumes:
      - rust_tool_logs:/app/logs
      - rust_tool_data:/app/data
    # Docker container log rotation settings
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    # Example for CLI mode
    # command: ["/app/rust-tool-template", "-m", "cli", "-c", "stats"]

  # Example for running in Japanese
  rust-tool-template-ja:
    build: .
    container_name: rust-tool-template-ja
    restart: unless-stopped
    environment:
      - RUST_LOG=rust_tool_template=info
      - RUST_TOOL_LANG=ja
      - RUST_BACKTRACE=1
    volumes:
      - rust_tool_logs_ja:/app/logs
      - rust_tool_data_ja:/app/data
    # Docker container log rotation settings
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    profiles:
      - japanese
    # command: ["/app/rust-tool-template", "-l", "ja"]

volumes:
  rust_tool_logs:
    driver: local
  rust_tool_data:
    driver: local
  rust_tool_logs_ja:
    driver: local
  rust_tool_data_ja:
    driver: local
