version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    command: python -m src.web.app
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped 