# Rust formatting configuration for modern Rust development

# Edition
edition = "2021"

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import organization
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Function and struct formatting
fn_single_line = false
where_single_line = false
force_explicit_abi = true

# Control flow formatting
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"

# Comments and documentation
wrap_comments = true
comment_width = 80
doc_comment_code_block_width = 100

# Expressions
chain_width = 60
single_line_if_else_max_width = 50

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Modern Rust features
use_field_init_shorthand = true
use_try_shorthand = true
